### ISSUE TITLE
[META] How-Tos

### ISSUE THREAD

**Issue by DannyS03** [availproject/availproject.github.io#89]
## Context

This meta-issue is designed to oversee the creation and revamping of How-To guides for various use-cases and node deployment scenarios within the Avail ecosystem. The primary objective is to offer comprehensive, accurate, and user-friendly documentation that enables users and developers to effectively utilize Avail as a data availability layer for modular solutions like Validiums, Rollups, App-chains, and more.

### New How-To Guides

- [ ] **Create an initial How-To for Validiums**: A step-by-step guide to using Avail as a data availability layer for Validiums: #88
- [ ] **Create an initial How-To for Rollups**: A comprehensive guide on leveraging Avail for Rollups.
- [ ] **Create an initial How-To for App-chains**: Detailed instructions for utilizing Avail in App-chains.

### Existing Guides

The existing guides for node deployment need an audit to ensure they are up-to-date, accurate, and have consistency.

- [ ] **Light Client**: Audit and update the existing guide.
- [ ] **Full Node**: Audit and update the existing guide.
- [ ] **Validator Guide**: Audit and update the existing guide.
- [ ] **Bootstrap Node**: Audit and update the existing guide.
- [ ] **Relay Node**: Audit and update the existing guide.
